from typing import AsyncGenerator, Optional, Protocol


class BaseBroker(Protocol):
    # NOTE: should be async def, but conflicts with lack of yield statement, which implementers would have
    def aprocess_notify(self, connected_callback=None) -> AsyncGenerator[tuple[str, str], None]: ...

    async def apublish_message(self, channel: Optional[str] = None, message: str = '') -> None: ...

    async def aclose(self) -> None: ...

    def publish_message(self, channel=None, message=None): ...

    def close(self): ...
