from typing import Optional, Protocol


class BaseBroker(Protocol):
    async def aprocess_notify(self, connected_callback=None): ...

    async def apublish_message(self, channel: Optional[str] = None, message: str = '') -> None: ...

    async def aclose(self) -> None: ...

    def publish_message(self, channel=None, message=None): ...

    def close(self): ...
